// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209115613_ResimUrlEklendi")]
    partial class ResimUrlEklendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("backend.Models.Ekipman", b =>
                {
                    b.Property<int>("EkipmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("EkipmanAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("LabID")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("text");

                    b.HasKey("EkipmanID");

                    b.HasIndex("LabID");

                    b.ToTable("Ekipmanlar");
                });

            modelBuilder.Entity("backend.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("boolean");

                    b.Property<string>("SifreHash")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("backend.Models.KullaniciRol", b =>
                {
                    b.Property<int>("KullaniciID")
                        .HasColumnType("integer");

                    b.Property<int>("RolID")
                        .HasColumnType("integer");

                    b.HasKey("KullaniciID", "RolID");

                    b.HasIndex("RolID");

                    b.ToTable("KullaniciRolleri");
                });

            modelBuilder.Entity("backend.Models.Laboratuvar", b =>
                {
                    b.Property<int>("LabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("LabAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SorumluID")
                        .HasColumnType("integer");

                    b.HasKey("LabID");

                    b.HasIndex("SorumluID");

                    b.ToTable("Laboratuvarlar");
                });

            modelBuilder.Entity("backend.Models.Rapor", b =>
                {
                    b.Property<int>("RaporID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DosyaAdi")
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaporBasligi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RezervasyonID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("YukleyenID")
                        .HasColumnType("integer");

                    b.HasKey("RaporID");

                    b.HasIndex("RezervasyonID")
                        .IsUnique();

                    b.HasIndex("YukleyenID");

                    b.ToTable("Raporlar");
                });

            modelBuilder.Entity("backend.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("EkipmanID")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("integer");

                    b.HasKey("RezervasyonID");

                    b.HasIndex("EkipmanID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("RolAdi")
                        .HasColumnType("text");

                    b.HasKey("RolID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("backend.Models.Ekipman", b =>
                {
                    b.HasOne("backend.Models.Laboratuvar", "Laboratuvar")
                        .WithMany("Ekipmanlar")
                        .HasForeignKey("LabID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Laboratuvar");
                });

            modelBuilder.Entity("backend.Models.KullaniciRol", b =>
                {
                    b.HasOne("backend.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("backend.Models.Laboratuvar", b =>
                {
                    b.HasOne("backend.Models.Kullanici", "Sorumlu")
                        .WithMany("SorumluOlduguLablar")
                        .HasForeignKey("SorumluID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sorumlu");
                });

            modelBuilder.Entity("backend.Models.Rapor", b =>
                {
                    b.HasOne("backend.Models.Rezervasyon", "Rezervasyon")
                        .WithOne("Rapor")
                        .HasForeignKey("backend.Models.Rapor", "RezervasyonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Kullanici", "Yukleyen")
                        .WithMany()
                        .HasForeignKey("YukleyenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");

                    b.Navigation("Yukleyen");
                });

            modelBuilder.Entity("backend.Models.Rezervasyon", b =>
                {
                    b.HasOne("backend.Models.Ekipman", "Ekipman")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("EkipmanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Kullanici", "Kullanici")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("backend.Models.Ekipman", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("backend.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciRolleri");

                    b.Navigation("Rezervasyonlar");

                    b.Navigation("SorumluOlduguLablar");
                });

            modelBuilder.Entity("backend.Models.Laboratuvar", b =>
                {
                    b.Navigation("Ekipmanlar");
                });

            modelBuilder.Entity("backend.Models.Rezervasyon", b =>
                {
                    b.Navigation("Rapor");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });
#pragma warning restore 612, 618
        }
    }
}
